name: Integration Tests

on: [ push, pull_request ]

jobs:

  Azure-Storage-Integration-Test:
    runs-on: ubuntu-latest

    env:
      RUN_INTEGRATION_TEST: true
      EDC_CORE_GITHUB_ACTOR: ${{ secrets.EDC_CORE_GITHUB_ACTOR }}
      EDC_CORE_GITHUB_TOKEN: ${{ secrets.EDC_CORE_GITHUB_TOKEN }}

    services:
      azurite:
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
          - 10000:10000
        env:
          AZURITE_ACCOUNTS: account1:key1;account2:key2

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Data Plane Azure Storage Test
        run: ./gradlew extensions:azure:data-plane-azure-storage:check

      - name: Object Storage StatusChecker Test
        run: ./gradlew extensions:azure:blobstorage:blob-provision:check

  Azure-CosmosDB-Integration-Test:
    runs-on: windows-2019

    env:
      RUN_INTEGRATION_TEST: true
      EDC_CORE_GITHUB_ACTOR: ${{ secrets.EDC_CORE_GITHUB_ACTOR }}
      EDC_CORE_GITHUB_TOKEN: ${{ secrets.EDC_CORE_GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Gradle cache
        uses: gradle/gradle-build-action@v2

      # Cosmos DB Emulator is preinstalled on GitHub Actions workers
      - name: Launch Cosmos DB Emulator
        run: |
          Import-Module "$env:ProgramFiles\Azure Cosmos DB Emulator\PSModules\Microsoft.Azure.CosmosDB.Emulator"
          Start-CosmosDbEmulator -Timeout 1200

      - name: CosmosDB Transfer Process Store Test
        run: ./gradlew extensions:azure:cosmos:transfer-process-store-cosmos:test

      - name: Cosmos-based Asset Index test
        run: ./gradlew extensions:azure:cosmos:assetindex-cosmos:test

      - name: Cosmos-based FCN Directory test
        run: ./gradlew extensions:azure:cosmos:transfer-process-store-cosmos:test

      - name: Cosmos-based ContractDefinitionStore Test
        run: ./gradlew extensions:azure:cosmos:contract-definition-store-cosmos:test

      - name: Cosmos-based ContractNegotiationStore Test
        run: ./gradlew extensions:azure:cosmos:contract-negotiation-store-cosmos:test
